---
services:
  astral:
    image: ghcr.io/kevinharv/create-astral-docker:master
    # build: .
    container_name: astral-server
    restart: "unless-stopped"
    stop_grace_period: 1m
    environment:
      - EULA=true
    env_file:
      - server_properties.env
    ports:
      - 25565:25565
    healthcheck:
      test: ["CMD", "rcon-cli", "-c", "/etc/rcon.yaml", "list"]
      interval: 1m
      timeout: 10s
      retries: 5
      start_period: 3m
    volumes:
      - worldData:/server/world

volumes:
  worldData:
